# Generated by Django 4.0.5 on 2022-06-24 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0003_alter_stock_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 21, 31, 45, 142938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Furniture', 'Furniture'), ('IT Equipment', 'IT Equipment'), ('ELECTRONICS', 'ELECTRONICS')], max_length=50, null=True),
        ),
    ]
