# Generated by Django 4.0.5 on 2022-06-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0006_stockhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('FURNITURE', 'FURNITURE'), ('IT EQUIPMENT', 'IT EQUIPMENT'), ('ELECTRONICS', 'ELECTRONICS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='category',
            field=models.CharField(blank=True, choices=[('FURNITURE', 'FURNITURE'), ('IT EQUIPMENT', 'IT EQUIPMENT'), ('ELECTRONICS', 'ELECTRONICS')], max_length=50, null=True),
        ),
    ]
